<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$this->headLink()->appendStylesheet($this->assetUrl('css/lightslider.min.css'));
$this->headLink()->appendStylesheet($this->assetUrl('css/lightgallery.min.css'));
$this->headScript()->appendFile($this->assetUrl('js/lightslider.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/lightgallery.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/lg-video.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/lg-zoom.js'));
$lightMedia = [];
$otherMedia = [];
foreach ($item->media() as $media) {
    $mediaType = $media->mediaType();
    $mediaRenderer = $media->renderer();
    if ((strpos($mediaType, 'image/') !== false) || (strpos($mediaRenderer, 'youtube') !== false)) {
        $lightMedia[] = $media;
    } else {
        $otherMedia[] = $media;
    }
}
?>
<center><?php echo $this->pageTitle($item->displayTitle(), 2); ?></center>
<?php if (count($lightMedia) > 0): ?>
<ul id="itemfiles" class="media-list">
    <?php foreach ($lightMedia as $media): ?>
        <?php $source = ($media->originalUrl()) ? $media->originalUrl() : $media->source(); ?>
        <li data-src="<?php echo $source; ?>" data-thumb="<?php echo $escape($media->thumbnailUrl('square')); ?>" class="media resource">
            <?php echo $media->render(); ?>
        </li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>
<?php echo $item->displayValues(); ?>
<?php if (count($otherMedia) > 0): ?>
 <div id="other-media" class="property">
    <h4><?php echo $this->translate('Other Media'); ?></h4>
    <div class="values">
        <?php foreach($otherMedia as $media): ?>
        <div class="value">
            <a href="<?php echo $media->siteUrl(); ?>"><?php echo $media->displayTitle(); ?></a>
        </div>
    </div>
    <?php endforeach; ?>
</div>
<?php endif; ?>
<?php
$page = $this->params()->fromQuery('page', 1);
$property = $this->params()->fromQuery('property');
$subjectValues = $item->displaySubjectValues($page, 25, $property);
?>
<?php if ($subjectValues): ?>
<div id="item-linked">
    <h3><?php echo $this->translate('Linked resources'); ?></h3>
    <?php echo $subjectValues; ?>
</div>
<?php endif; ?>
<?php $this->trigger('view.show.after'); ?>
