<?php
$this->htmlElement('body')->appendAttribute('class', 'media resource show');
$mediaType = $media->mediaType();
$enableLightGallery = strpos($mediaType, 'image/') !== false || (strpos($media->renderer(), 'youtube') !== false);
if ($enableLightGallery) {
    $this->headLink()->appendStylesheet($this->assetUrl('css/lightslider.min.css'));
    $this->headLink()->appendStylesheet($this->assetUrl('css/lightgallery.min.css'));
    $this->headScript()->appendFile($this->assetUrl('js/lightslider.min.js'));
    $this->headScript()->appendFile($this->assetUrl('js/lightgallery.min.js'));
    $this->headScript()->appendFile($this->assetUrl('js/lg-video.min.js'));
    $this->headScript()->appendFile($this->assetUrl('js/lg-zoom.js'));
}
?>
<?php echo $this->pageTitle($media->displayTitle(), 2); ?>
<h3><?php echo $this->translate('Media'); ?></h3>
<?php $this->trigger('view.show.before'); ?>
<?php if ($enableLightGallery): ?>
    <?php $source = ($media->originalUrl()) ? $media->originalUrl() : $media->source(); ?>
<ul id="itemfiles">
    <li data-src="<?php echo $source; ?>" data-thumb="<?php echo $this->escapeHtml($media->thumbnailUrl('square')); ?>" class="media resource">
        <?php echo $media->render(); ?>
    </li>
</ul>
<?php else: ?>
    <?php echo $media->render(); ?>
<?php endif; ?>
<?php echo $media->displayValues(); ?>
<?php $this->trigger('view.show.after'); ?>
