<?php
$translate = $this->plugin('translate');
$hyperlink = $this->plugin('hyperlink');
$url = $this->plugin('url');
$this->htmlElement('body')->appendAttribute('class', 'index search');
?>

<?php echo $this->pageTitle(sprintf($this->translate('Search results for “%s”'), $query)); ?>

<div>
    <h2><?php echo 'Objets' ; ?></h2>
    <?php if ($items): ?>

    <?php echo $this->hyperlink(
        sprintf($this->translate('Voir tous les résultats'), $itemsTotal),
        $this->url(
            'site/resource',
            ['controller' => 'item', 'action' => 'browse'],
            ['query' => ['fulltext_search' => $query]],
            true
        )
    ); ?>

<ul class="resource-list">
    <?php foreach ($items as $item): ?>
    <li class="item resource">
        <?php if ($volumeNumber = $item->value('schema:volumeNumber')): ?>
        <div class="volumeNumber"><?php echo 'Vol. n. ' ?><?php echo $volumeNumber; ?></div>
        <?php endif; ?>
        <?php if ($thumbnail = $this->thumbnail($item, 'medium')): ?>
        <?php echo '<center>'; echo $item->linkRaw($thumbnail); echo '</center>';?>
        <?php endif; ?>
        <div class="customIcones">
        <?php if ($creation = $item->value('vra:locationCreationSite')): ?>
        <div class="customLocalisation"><?php echo '<img title="Lieu de création : '?><?php echo $creation ?><?php echo '" src="https://digitalmuret.inha.fr/themes/DigitalMuret/asset/img/compass_icon.png" />'; ?></div>
        <?php endif; ?>
        <?php if ($discovery = $item->value('vra:locationDiscoverySite')): ?>
        <div class="customLocalisation"><?php echo '<img title="Lieu de découverte : '?><?php echo $discovery ?><?php echo '" src="https://digitalmuret.inha.fr/themes/DigitalMuret/asset/img/trowel2_icon.png" />'; ?></div>
        <?php endif; ?>
        <?php if ($location = $item->value('schema:location')): ?>
        <div class="customLocalisation"><?php echo '<img title="Lieu de conservation : '?><?php echo $location ?><?php echo '" src="https://digitalmuret.inha.fr/themes/DigitalMuret/asset/img/musee2_icon.png" />'; ?></div>
        <?php endif; ?>
        </div>
        <p class="customType"><b><?php echo $item->value('dcterms:type'); ?></b></p>
        <div class='browseTitre'><center><h4><?php echo $item->link($item->value('dcterms:title')); ?></h4></center></div>
        <?php if ($description = $item->value('dcterms:description')): ?>
        <div class="description"><?php echo mb_substr($description,0,75); echo $item->link('...'); ?></div></br>
        <?php endif; ?>
    </li>
    <?php endforeach; ?>
</ul>

    <?php echo $this->hyperlink(
        sprintf($this->translate('Voir tous les résultats'), $itemsTotal),
        $this->url(
            'site/resource',
            ['controller' => 'item', 'action' => 'browse'],
            ['query' => ['fulltext_search' => $query]],
            true
        )
    ); ?>

    <?php else: ?>
    <p><?php echo $this->translate('Aucun objet a été trouvé'); ?></p>
    <?php endif; ?>
</div>

<div>
    <h2><?php echo 'Articles' ; ?></h2>
    <?php if ($pages): ?>
    <ul class="searchPages">
        <?php foreach ($pages as $page): ?>
        <li class="listPages"><h4><?php echo $page->link($page->title()); ?></h4></li>
        <?php endforeach; ?>
    </ul>
    <?php else: ?>
    <p><?php echo $this->translate('Aucun article a été trouvé'); ?></p>
    <?php endif; ?>
</div>