<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Crimson+Text:400,400italic,700,700italic');
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->appendStylesheet($this->assetUrl('css/style.css'));
$this->headScript()->prependFile($this->assetUrl('js/digitalMuret.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->trigger('view.layout');
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
        <link rel="icon" href="<?php echo ($this->assetUrl('/img/icons-192.gif')); ?>" type="image/gif" />
    </head>
    <?php echo $this->htmlElement('body'); ?>
        <a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>
        <?php echo $userBar; ?>
        <div id="wrap">
            <header>
                <?php if ($this->themeSetting('logo')): ?>
                <a href="<?php echo $site->url(); ?>" class="site-title"><img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" title="Logo"></a>
                <?php else: ?>
                <a href="<?php echo $site->url(); ?>" class="site-title"><?php echo $this->pageTitle($site->title()); ?></a>
                <?php endif; ?>
                <div id="search-container">
                    <?php echo $this->partial('common/search-form'); ?>
                    <button type="button" class="search-toggle" title="Toggle search"></button>
                </div>
                <nav class="main-navigation">
                    <div class="nav-wrapper">
                        <input type="checkbox" class="menu-checkbox" />
                        <label for="menu-checkbox" class="menu-toggle">    Menu</label>
                <?php
                echo $site->publicNav()->menu()->renderMenu(null, [
                    'maxDepth' => $this->themeSetting('nav_depth') - 1
                ]);
                ?>
                    </div>
                </nav>
            </header>
            <div id="content" role="main">
                <?php echo $this->content; ?>
            </div>
            <footer>
                <nav><ul class="navigation"><li><a href="<?php echo $site->url(); ?>/page/about">À propos</a></li><li><a href="<?php echo $site->url(); ?>/page/partenaires">Partenaires</a></li><li><a href="<?php echo $site->url(); ?>/page/mentions-legales">Mentions légales</a></li><li><a href="<?php echo $site->url(); ?>/page/carte">Carte des objets</a></li></ul></nav>
                <button onclick="topFunction()" id="buttonTop" class="topButton" title="Haut de page"><span class="legend"><i class="fas fa-arrow-up"></i></span></button>
            </footer>
        </div>
        <script>
        window.onscroll = function() {scrollFunction()};
            function scrollFunction() {
            if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
                document.getElementById("buttonTop").style.display = "block";
            } else {
                document.getElementById("buttonTop").style.display = "none";
                }
            }
            function topFunction() {
            document.body.scrollTop = 0;
            document.documentElement.scrollTop = 0;
            }
        </script>
        </body>
</html>
